volumes:
  site-db:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./site:/web-app:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf
    working_dir: /web-app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php-docker.file
    volumes:
      - ./site:/web-app
    working_dir: /web-app
    user: 1000:1000
    depends_on:
      - db

  db:
    image: mariadb:latest
    volumes:
      - site-db:/var/lib/mysql
      - ./dumps:/db-dumps
    working_dir: /db-dumps
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MARIADB_DATABASE: cbt



